# Giving aliases to actual tables in Snowflake.
# Here we're defining a single database and a single schema.
sources:
  - name: airbnb
    schema: raw
    tables:
      - name: listings
        identifier: raw_listings
        columns:
          - name: room_type
            data_tests:
              - dbt_expectations.expect_column_distinct_count_to_equal:
                  arguments:
                    value: 4
          - name: price
            data_tests:
              - dbt_expectations.expect_column_values_to_match_regex:
                  arguments:
                    # `^` means the value must start with a certain value.
                    # `$` is a special character in regex, so it must be escaped with `\`.
                    # But this is YAML (which picks up `\` as a special character), so we must use `\\`.
                    # Similar thing with other `\\`s.
                    # And then Snowflake also needs doube escaping,
                    # because it converts `\\` to `\` before passing to its regex engine.
                    # The final `$` means this should be the end of the string.
                    regex: "^\\\\$[0-9][0-9\\\\.]+$"

      - name: hosts
        identifier: raw_hosts

      - name: reviews
        identifier: raw_reviews
        config:
          loaded_at_field: date
          freshness:
            warn_after: {count: 1, period: hour}
            # error_after: {count: 24, period: hour}
